// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketIssue.Infrastructure.Context;

#nullable disable

namespace TicketIssue.Infrastructure.Context.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615142602_AddInitialMigration")]
    partial class AddInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketIssue.Domain.Entities.FareModification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FareModifications");
                });

            modelBuilder.Entity("TicketIssue.Domain.Entities.SoldProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DistanceInKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoldProducts");
                });

            modelBuilder.Entity("TicketIssue.Domain.Entities.SoldProductModification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AppliedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FareModificationId")
                        .HasColumnType("int");

                    b.Property<Guid>("SoldProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FareModificationId");

                    b.HasIndex("SoldProductId");

                    b.ToTable("SoldProductModifications");
                });

            modelBuilder.Entity("TicketIssue.Domain.Entities.SoldProductModification", b =>
                {
                    b.HasOne("TicketIssue.Domain.Entities.FareModification", "FareModification")
                        .WithMany()
                        .HasForeignKey("FareModificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketIssue.Domain.Entities.SoldProduct", "SoldProduct")
                        .WithMany("AppliedModifications")
                        .HasForeignKey("SoldProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FareModification");

                    b.Navigation("SoldProduct");
                });

            modelBuilder.Entity("TicketIssue.Domain.Entities.SoldProduct", b =>
                {
                    b.Navigation("AppliedModifications");
                });
#pragma warning restore 612, 618
        }
    }
}
